### ISSUE TITLE
A checklist for April 18th launch

### ISSUE THREAD

**Issue by qpzm** [elysia-dev/elyfi-stakingpool-v2#9]
- [x]  #7 
- [x] #8
- [ ] Is duration` modifiable? Currently, `poolData.endTimestamp = poolData.endTimestamp + poolData.duration;`.
- [ ] `migrate`
- Test
    - [ ] when the pool is closed, the staking reward should not be extended.

**Comment by sujine2** [comment]
_claim 함수의    uint256 rewardLeft = rewardAsset.balanceOf(address(this));     rewardAsset 이 같아지면서 잔고 확인 문제
